---
title: "CheckBlenAsymmetry"
author: "Xiang Ji"
date: "February 4, 2016"
output: html_document
---

Load data from All.RData

```{r}
rm(list=ls())  # clean up workspace
load("/Users/xji3/GitFolders/IGCCodonSimulation/All.RData")

paml.path <- "/Users/xji3/GitFolders/IGCCodonSimulation/"
IGC.geo.list <- c(3.0)

# Read in new PAML results
data.path <- paste(paralog, "",sep = "/")
for (IGC.geo in IGC.geo.list){
  summary_mat <- NULL
  IGC.geo.path <- paste("IGCgeo_", toString(IGC.geo), ".0/", sep = "")
  file.name <- paste("geo", paste(toString(IGC.geo), ".0", sep = ""), "estimatedTau", "paml", "unrooted", "1stTree", "summary.txt", sep = "_")
  for (sim.num in 0:(num.sim - 1)){
    summary_file <- paste(paml.path, file.name, sep = "")
    if (file.exists(summary_file)){
      all <- readLines(summary_file, n = -1)
      col.names <- strsplit(all[1], ' ')[[1]][-1]
      row.names <- strsplit(all[length(all)], ' ')[[1]][-1]
      summary_mat <- as.matrix(read.table(summary_file, 
                                          row.names = row.names, 
                                          col.names = col.names))
      
      }
    }
  assign(paste("PAML", "estimatedTau", paste(toString(IGC.geo), ".0", sep = ""), "1stTree", "summary", sep = "_"), summary_mat)
}

for (IGC.geo in IGC.geo.list){
  summary_mat <- NULL
  IGC.geo.path <- paste("IGCgeo_", toString(IGC.geo), ".0/", sep = "")
  file.name <- paste("geo", paste(toString(IGC.geo), ".0", sep = ""), "estimatedTau", "paml", "unrooted", "2ndTree", "summary.txt", sep = "_")
  for (sim.num in 0:(num.sim - 1)){
    summary_file <- paste(paml.path, file.name, sep = "")
    if (file.exists(summary_file)){
      all <- readLines(summary_file, n = -1)
      col.names <- strsplit(all[1], ' ')[[1]][-1]
      row.names <- strsplit(all[length(all)], ' ')[[1]][-1]
      summary_mat <- as.matrix(read.table(summary_file, 
                                          row.names = row.names, 
                                          col.names = col.names))
      
      }
    }
  assign(paste("PAML", "estimatedTau", paste(toString(IGC.geo), ".0", sep = ""), "2ndTree", "summary", sep = "_"), summary_mat)
}

for (IGC.geo in IGC.geo.list){
  summary_mat <- NULL
  IGC.geo.path <- paste("IGCgeo_", toString(IGC.geo), ".0/", sep = "")
  file.name <- paste("geo", paste(toString(IGC.geo), ".0", sep = ""), "10Tau", "paml", "unrooted", "1stTree", "summary.txt", sep = "_")
  for (sim.num in 0:(num.sim - 1)){
    summary_file <- paste(paml.path, file.name, sep = "")
    if (file.exists(summary_file)){
      all <- readLines(summary_file, n = -1)
      col.names <- strsplit(all[1], ' ')[[1]][-1]
      row.names <- strsplit(all[length(all)], ' ')[[1]][-1]
      summary_mat <- as.matrix(read.table(summary_file, 
                                          row.names = row.names, 
                                          col.names = col.names))
      
      }
    }
  assign(paste("PAML", "10Tau", paste(toString(IGC.geo), ".0", sep = ""), "1stTree", "summary", sep = "_"), summary_mat)
  }

for (IGC.geo in IGC.geo.list){
  summary_mat <- NULL
  IGC.geo.path <- paste("IGCgeo_", toString(IGC.geo), ".0/", sep = "")
  file.name <- paste("geo", paste(toString(IGC.geo), ".0", sep = ""), "10Tau", "paml", "unrooted", "2ndTree", "summary.txt", sep = "_")
  for (sim.num in 0:(num.sim - 1)){
    summary_file <- paste(paml.path, file.name, sep = "")
    if (file.exists(summary_file)){
      all <- readLines(summary_file, n = -1)
      col.names <- strsplit(all[1], ' ')[[1]][-1]
      row.names <- strsplit(all[length(all)], ' ')[[1]][-1]
      summary_mat <- as.matrix(read.table(summary_file, 
                                          row.names = row.names, 
                                          col.names = col.names))
      
      }
    }
  assign(paste("PAML", "10Tau", paste(toString(IGC.geo), ".0", sep = ""), "2ndTree", "summary", sep = "_"), summary_mat)
}

# save.image("/Users/xji3/GitFolders/IGCCodonSimulation/All.RData")
```

#### Feb 5 update

Check PAML estimate of two same tree topologies but different order of taxa

```{r}
# Simulation using estimated Tau value of 1.409408
# Look at difference of each estimate (Tree 1 - Tree 2)

# log likelihood
summary(PAML_estimatedTau_3.0_1stTree_summary["ll", ] - PAML_estimatedTau_3.0_2ndTree_summary["ll", ])
sd(PAML_estimatedTau_3.0_1stTree_summary["ll", ] - PAML_estimatedTau_3.0_2ndTree_summary["ll", ])
# kappa
summary(PAML_estimatedTau_3.0_1stTree_summary["kappa", ] - PAML_estimatedTau_3.0_2ndTree_summary["kappa", ])
sd(PAML_estimatedTau_3.0_1stTree_summary["kappa", ] - PAML_estimatedTau_3.0_2ndTree_summary["kappa", ])
# omega
summary(PAML_estimatedTau_3.0_1stTree_summary["omega", ] - PAML_estimatedTau_3.0_2ndTree_summary["omega", ])
sd(PAML_estimatedTau_3.0_1stTree_summary["omega", ] - PAML_estimatedTau_3.0_2ndTree_summary["omega", ])
# N0_kluyveriYDR418W
summary(PAML_estimatedTau_3.0_1stTree_summary["N0_kluyveriYDR418W", ] - PAML_estimatedTau_3.0_2ndTree_summary["N0_kluyveriYDR418W", ])
sd(PAML_estimatedTau_3.0_1stTree_summary["N0_kluyveriYDR418W", ] - PAML_estimatedTau_3.0_2ndTree_summary["N0_kluyveriYDR418W", ])
# N0_N1
summary(PAML_estimatedTau_3.0_1stTree_summary["N0_N1", ] - PAML_estimatedTau_3.0_2ndTree_summary["N0_N6", ])
sd(PAML_estimatedTau_3.0_1stTree_summary["N0_N1", ] - PAML_estimatedTau_3.0_2ndTree_summary["N0_N6", ])
```

There seems no difference between two different tree representations

Now check PAML results on simulation with 10*Tau 

```{r}
# Simulation using 10 * Tau value of 1.409408 * 10 = 14.09408
# Look at difference of each estimate (Tree 1 - Tree 2)

# log likelihood
summary(PAML_10Tau_3.0_1stTree_summary["ll", ] - PAML_10Tau_3.0_2ndTree_summary["ll", ])
sd(PAML_10Tau_3.0_1stTree_summary["ll", ] - PAML_10Tau_3.0_2ndTree_summary["ll", ])
hist(PAML_10Tau_3.0_1stTree_summary["ll", ] - PAML_10Tau_3.0_2ndTree_summary["ll", ])
# kappa
summary(PAML_10Tau_3.0_1stTree_summary["kappa", ] - PAML_10Tau_3.0_2ndTree_summary["kappa", ])
sd(PAML_10Tau_3.0_1stTree_summary["kappa", ] - PAML_10Tau_3.0_2ndTree_summary["kappa", ])
# omega
summary(PAML_10Tau_3.0_1stTree_summary["omega", ] - PAML_10Tau_3.0_2ndTree_summary["omega", ])
sd(PAML_10Tau_3.0_1stTree_summary["omega", ] - PAML_10Tau_3.0_2ndTree_summary["omega", ])
# N0_kluyveriYDR418W
summary(PAML_10Tau_3.0_1stTree_summary["N0_kluyveriYDR418W", ] - PAML_10Tau_3.0_2ndTree_summary["N0_kluyveriYDR418W", ])
sd(PAML_10Tau_3.0_1stTree_summary["N0_kluyveriYDR418W", ] - PAML_10Tau_3.0_2ndTree_summary["N0_kluyveriYDR418W", ])
# N0_N1
summary(PAML_10Tau_3.0_1stTree_summary["N0_N1", ] - PAML_10Tau_3.0_2ndTree_summary["N0_N6", ])
sd(PAML_10Tau_3.0_1stTree_summary["N0_N1", ] - PAML_10Tau_3.0_2ndTree_summary["N0_N6", ])
# N1_N2
summary(PAML_10Tau_3.0_1stTree_summary["N1_N2", ] - PAML_10Tau_3.0_2ndTree_summary["N6_N7", ])
sd(PAML_10Tau_3.0_1stTree_summary["N1_N2", ] - PAML_10Tau_3.0_2ndTree_summary["N6_N7", ])
hist(PAML_10Tau_3.0_1stTree_summary["N1_N2", ] - PAML_10Tau_3.0_2ndTree_summary["N6_N7", ])
# N1_castelliiYDR418W
summary(PAML_10Tau_3.0_1stTree_summary["N1_castelliiYDR418W", ] - PAML_10Tau_3.0_2ndTree_summary["N6_castelliiYDR418W", ])
sd(PAML_10Tau_3.0_1stTree_summary["N1_castelliiYDR418W", ] - PAML_10Tau_3.0_2ndTree_summary["N6_castelliiYDR418W", ])
hist(PAML_10Tau_3.0_1stTree_summary["N1_castelliiYDR418W", ] - PAML_10Tau_3.0_2ndTree_summary["N6_castelliiYDR418W", ])
# N2_N3
summary(PAML_10Tau_3.0_1stTree_summary["N2_N3", ] - PAML_10Tau_3.0_2ndTree_summary["N7_N8", ])
sd(PAML_10Tau_3.0_1stTree_summary["N2_N3", ] - PAML_10Tau_3.0_2ndTree_summary["N7_N8", ])
hist(PAML_10Tau_3.0_1stTree_summary["N2_N3", ] - PAML_10Tau_3.0_2ndTree_summary["N7_N8", ])
# N2_N3
summary(PAML_10Tau_3.0_1stTree_summary["N2_N3", ] - PAML_10Tau_3.0_2ndTree_summary["N7_N8", ])
sd(PAML_10Tau_3.0_1stTree_summary["N2_N3", ] - PAML_10Tau_3.0_2ndTree_summary["N7_N8", ])
hist(PAML_10Tau_3.0_1stTree_summary["N2_N3", ] - PAML_10Tau_3.0_2ndTree_summary["N7_N8", ])
# N2_bayanusYDR418W
summary(PAML_10Tau_3.0_1stTree_summary["N2_bayanusYDR418W", ] - PAML_10Tau_3.0_2ndTree_summary["N7_bayanusYDR418W", ])
sd(PAML_10Tau_3.0_1stTree_summary["N2_bayanusYDR418W", ] - PAML_10Tau_3.0_2ndTree_summary["N7_bayanusYDR418W", ])
hist(PAML_10Tau_3.0_1stTree_summary["N2_bayanusYDR418W", ] - PAML_10Tau_3.0_2ndTree_summary["N7_bayanusYDR418W", ])

```
Now start to check branches ratio of subtree branches of paralog 1 over paralog 2 ratios

```{r}
# N0_N1
target <- PAML_3.0_summary["N0_N1", ] / PAML_3.0_summary["N0_N6", ]
hist(target, main = "N0_N1"); mean(target); sd(target)

# N1_N2
target <- PAML_3.0_summary["N1_N2", ] / PAML_3.0_summary["N6_N7", ]
hist(target, main = "N1_N2"); mean(target); sd(target)

# N1_castellii
target <- PAML_3.0_summary["N1_castelliiYDR418W", ] / PAML_3.0_summary["N6_castelliiYEL054C", ]
hist(target, main = "N1_castellii"); mean(target); sd(target)

# N2_N3
target <- PAML_3.0_summary["N2_N3", ] / PAML_3.0_summary["N7_N8", ]
hist(target, main = "N2_N3"); mean(target); sd(target)

# N2_bayanus
target <- PAML_3.0_summary["N2_bayanusYDR418W", ] / PAML_3.0_summary["N7_bayanusYEL054C", ]
hist(target, main = "N2_bayanus"); mean(target); sd(target)

# N3_N4
target <- PAML_3.0_summary["N3_N4", ] / PAML_3.0_summary["N8_N9", ]
hist(target, main = "N3_N4"); mean(target); sd(target)

# N3_kudriavzevii
target <- PAML_3.0_summary["N3_kudriavzeviiYDR418W", ] / PAML_3.0_summary["N8_kudriavzeviiYEL054C", ]
hist(target, main = "N3_kudriavzevii"); mean(target); sd(target)

# N4_N5
target <- PAML_3.0_summary["N4_N5", ] / PAML_3.0_summary["N9_N10", ]
hist(target, main = "N4_N5"); mean(target); sd(target)

# N4_mikatae
target <- PAML_3.0_summary["N4_mikataeYDR418W", ] / PAML_3.0_summary["N9_mikataeYEL054C", ]  # paralog 1 / paralog 2
hist(target, main = "N4_mikatae"); mean(target); sd(target)

# N5_paradoxus
target <- PAML_3.0_summary["N5_paradoxusYDR418W", ] / PAML_3.0_summary["N10_paradoxusYEL054C", ]  # paralog 1 / paralog 2
hist(target, main = "N5_paradoxus"); mean(target); sd(target)

# N5_cerevisiae
target <- PAML_3.0_summary["N5_cerevisiaeYDR418W", ] / PAML_3.0_summary["N10_cerevisiaeYEL054C", ]  # paralog 1 / paralog 2
hist(target, main = "N5_cerevisiae"); mean(target); sd(target)
 
# N0_N1
target <- PAML_10.0_summary["N0_N1", ] / PAML_10.0_summary["N0_N6", ]
hist(target, main = "N0_N1"); mean(target); sd(target)

# N1_N2
target <- PAML_10.0_summary["N1_N2", ] / PAML_10.0_summary["N6_N7", ]
hist(target, main = "N1_N2"); mean(target); sd(target)

# N1_castellii
target <- PAML_10.0_summary["N1_castelliiYDR418W", ] / PAML_10.0_summary["N6_castelliiYEL054C", ]
hist(target, main = "N1_castellii"); mean(target); sd(target)

# N2_N3
target <- PAML_10.0_summary["N2_N3", ] / PAML_10.0_summary["N7_N8", ]
hist(target, main = "N2_N3"); mean(target); sd(target)

# N2_bayanus
target <- PAML_10.0_summary["N2_bayanusYDR418W", ] / PAML_10.0_summary["N7_bayanusYEL054C", ]
hist(target, main = "N2_bayanus"); mean(target); sd(target)

# N3_N4
target <- PAML_10.0_summary["N3_N4", ] / PAML_10.0_summary["N8_N9", ]
hist(target, main = "N3_N4"); mean(target); sd(target)

# N3_kudriavzevii
target <- PAML_10.0_summary["N3_kudriavzeviiYDR418W", ] / PAML_10.0_summary["N8_kudriavzeviiYEL054C", ]
hist(target, main = "N3_kudriavzevii"); mean(target); sd(target)

# N4_N5
target <- PAML_10.0_summary["N4_N5", ] / PAML_10.0_summary["N9_N10", ]
hist(target, main = "N4_N5"); mean(target); sd(target)

# N4_mikatae
target <- PAML_10.0_summary["N4_mikataeYDR418W", ] / PAML_10.0_summary["N9_mikataeYEL054C", ]  # paralog 1 / paralog 2
hist(target, main = "N4_mikatae"); mean(target); sd(target)

# N5_paradoxus
target <- PAML_10.0_summary["N5_paradoxusYDR418W", ] / PAML_10.0_summary["N10_paradoxusYEL054C", ]  # paralog 1 / paralog 2
hist(target, main = "N5_paradoxus"); mean(target); sd(target)

# N5_cerevisiae
target <- PAML_10.0_summary["N5_cerevisiaeYDR418W", ] / PAML_10.0_summary["N10_cerevisiaeYEL054C", ]  # paralog 1 / paralog 2
hist(target, main = "N5_cerevisiae"); mean(target); sd(target)
 
# N0_N1
target <- PAML_50.0_summary["N0_N1", ] / PAML_50.0_summary["N0_N6", ]
hist(target, main = "N0_N1"); mean(target); sd(target)

# N1_N2
target <- PAML_50.0_summary["N1_N2", ] / PAML_50.0_summary["N6_N7", ]
hist(target, main = "N1_N2"); mean(target); sd(target)

# N1_castellii
target <- PAML_50.0_summary["N1_castelliiYDR418W", ] / PAML_50.0_summary["N6_castelliiYEL054C", ]
hist(target, main = "N1_castellii"); mean(target); sd(target)

# N2_N3
target <- PAML_50.0_summary["N2_N3", ] / PAML_50.0_summary["N7_N8", ]
hist(target, main = "N2_N3"); mean(target); sd(target)

# N2_bayanus
target <- PAML_50.0_summary["N2_bayanusYDR418W", ] / PAML_50.0_summary["N7_bayanusYEL054C", ]
hist(target, main = "N2_bayanus"); mean(target); sd(target)

# N3_N4
target <- PAML_50.0_summary["N3_N4", ] / PAML_50.0_summary["N8_N9", ]
hist(target, main = "N3_N4"); mean(target); sd(target)

# N3_kudriavzevii
target <- PAML_50.0_summary["N3_kudriavzeviiYDR418W", ] / PAML_50.0_summary["N8_kudriavzeviiYEL054C", ]
hist(target, main = "N3_kudriavzevii"); mean(target); sd(target)

# N4_N5
target <- PAML_50.0_summary["N4_N5", ] / PAML_50.0_summary["N9_N10", ]
hist(target, main = "N4_N5"); mean(target); sd(target)

# N4_mikatae
target <- PAML_50.0_summary["N4_mikataeYDR418W", ] / PAML_50.0_summary["N9_mikataeYEL054C", ]  # paralog 1 / paralog 2
hist(target, main = "N4_mikatae"); mean(target); sd(target)

# N5_paradoxus
target <- PAML_50.0_summary["N5_paradoxusYDR418W", ] / PAML_50.0_summary["N10_paradoxusYEL054C", ]  # paralog 1 / paralog 2
hist(target, main = "N5_paradoxus"); mean(target); sd(target)

# N5_cerevisiae
target <- PAML_50.0_summary["N5_cerevisiaeYDR418W", ] / PAML_50.0_summary["N10_cerevisiaeYEL054C", ]  # paralog 1 / paralog 2
hist(target, main = "N5_cerevisiae"); mean(target); sd(target)
 # N0_N1
target <- PAML_100.0_summary["N0_N1", ] / PAML_100.0_summary["N0_N6", ]
hist(target, main = "N0_N1"); mean(target); sd(target)

# N1_N2
target <- PAML_100.0_summary["N1_N2", ] / PAML_100.0_summary["N6_N7", ]
hist(target, main = "N1_N2"); mean(target); sd(target)

# N1_castellii
target <- PAML_100.0_summary["N1_castelliiYDR418W", ] / PAML_100.0_summary["N6_castelliiYEL054C", ]
hist(target, main = "N1_castellii"); mean(target); sd(target)

# N2_N3
target <- PAML_100.0_summary["N2_N3", ] / PAML_100.0_summary["N7_N8", ]
hist(target, main = "N2_N3"); mean(target); sd(target)

# N2_bayanus
target <- PAML_100.0_summary["N2_bayanusYDR418W", ] / PAML_100.0_summary["N7_bayanusYEL054C", ]
hist(target, main = "N2_bayanus"); mean(target); sd(target)

# N3_N4
target <- PAML_100.0_summary["N3_N4", ] / PAML_100.0_summary["N8_N9", ]
hist(target, main = "N3_N4"); mean(target); sd(target)

# N3_kudriavzevii
target <- PAML_100.0_summary["N3_kudriavzeviiYDR418W", ] / PAML_100.0_summary["N8_kudriavzeviiYEL054C", ]
hist(target, main = "N3_kudriavzevii"); mean(target); sd(target)

# N4_N5
target <- PAML_100.0_summary["N4_N5", ] / PAML_100.0_summary["N9_N10", ]
hist(target, main = "N4_N5"); mean(target); sd(target)

# N4_mikatae
target <- PAML_100.0_summary["N4_mikataeYDR418W", ] / PAML_100.0_summary["N9_mikataeYEL054C", ]  # paralog 1 / paralog 2
hist(target, main = "N4_mikatae"); mean(target); sd(target)

# N5_paradoxus
target <- PAML_100.0_summary["N5_paradoxusYDR418W", ] / PAML_100.0_summary["N10_paradoxusYEL054C", ]  # paralog 1 / paralog 2
hist(target, main = "N5_paradoxus"); mean(target); sd(target)

# N5_cerevisiae
target <- PAML_100.0_summary["N5_cerevisiaeYDR418W", ] / PAML_100.0_summary["N10_cerevisiaeYEL054C", ]  # paralog 1 / paralog 2
hist(target, main = "N5_cerevisiae"); mean(target); sd(target)
 # N0_N1
target <- PAML_500.0_summary["N0_N1", ] / PAML_500.0_summary["N0_N6", ]
hist(target, main = "N0_N1"); mean(target); sd(target)

# N1_N2
target <- PAML_500.0_summary["N1_N2", ] / PAML_500.0_summary["N6_N7", ]
hist(target, main = "N1_N2"); mean(target); sd(target)

# N1_castellii
target <- PAML_500.0_summary["N1_castelliiYDR418W", ] / PAML_500.0_summary["N6_castelliiYEL054C", ]
hist(target, main = "N1_castellii"); mean(target); sd(target)

# N2_N3
target <- PAML_500.0_summary["N2_N3", ] / PAML_500.0_summary["N7_N8", ]
hist(target, main = "N2_N3"); mean(target); sd(target)

# N2_bayanus
target <- PAML_500.0_summary["N2_bayanusYDR418W", ] / PAML_500.0_summary["N7_bayanusYEL054C", ]
hist(target, main = "N2_bayanus"); mean(target); sd(target)

# N3_N4
target <- PAML_500.0_summary["N3_N4", ] / PAML_500.0_summary["N8_N9", ]
hist(target, main = "N3_N4"); mean(target); sd(target)

# N3_kudriavzevii
target <- PAML_500.0_summary["N3_kudriavzeviiYDR418W", ] / PAML_500.0_summary["N8_kudriavzeviiYEL054C", ]
hist(target, main = "N3_kudriavzevii"); mean(target); sd(target)

# N4_N5
target <- PAML_500.0_summary["N4_N5", ] / PAML_500.0_summary["N9_N10", ]
hist(target, main = "N4_N5"); mean(target); sd(target)

# N4_mikatae
target <- PAML_500.0_summary["N4_mikataeYDR418W", ] / PAML_500.0_summary["N9_mikataeYEL054C", ]  # paralog 1 / paralog 2
hist(target, main = "N4_mikatae"); mean(target); sd(target)

# N5_paradoxus
target <- PAML_500.0_summary["N5_paradoxusYDR418W", ] / PAML_500.0_summary["N10_paradoxusYEL054C", ]  # paralog 1 / paralog 2
hist(target, main = "N5_paradoxus"); mean(target); sd(target)

# N5_cerevisiae
target <- PAML_500.0_summary["N5_cerevisiaeYDR418W", ] / PAML_500.0_summary["N10_cerevisiaeYEL054C", ]  # paralog 1 / paralog 2
hist(target, main = "N5_cerevisiae"); mean(target); sd(target)
 
 
```